version: '3.1'

services:
    app:
        image: openvidu/openvidu-js-screen-share-demo:2.22.0
        restart: on-failure
        network_mode: host
        environment:
            - APPLICATION_URL=https://${DOMAIN_OR_PUBLIC_IP:-}:${HTTPS_PORT:-443}